using MessagePack;

namespace WireBound.IPC.Messages;

/// <summary>
/// Server-to-client challenge sent immediately after the IPC channel opens.
/// Contains a cryptographically random nonce the client must include in its
/// subsequent <see cref="AuthenticateRequest"/>. Eliminates timestamp-based
/// replay windows in favour of a single-use server-issued nonce.
/// </summary>
[MessagePackObject]
public class ChallengeMessage
{
    /// <summary>
    /// 32 random bytes generated by the server for this connection. The
    /// client must echo them back in <see cref="AuthenticateRequest.Nonce"/>.
    /// </summary>
    [Key(0)]
    public byte[] Nonce { get; set; } = [];

    /// <summary>
    /// Unix timestamp (seconds) when the nonce expires. The server rejects
    /// authentication after this time.
    /// </summary>
    [Key(1)]
    public long ExpiresAtUtc { get; set; }
}
